### ISSUE TITLE
Remove allowBackup from manifest

### ISSUE THREAD

**Issue by dabarnard** [jhonnyx2012/HorizontalPicker#17]
Hi @jhonnyx2012 , thanks for your efforts with this library. It's been very helpful and I haven't found any other library that works as well as yours. I came across the following issue whilst using your lib and thought I would share some info:

If the library is used by any app which sets the value for _allowBackup_ to false within their manifest, the manifest merger will fail with an error similar to the one below:

`Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:10:9-36
	is also present at [com.github.jhonnyx2012:horizontal-picker:1.0.6] AndroidManifest.xml:12:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:8:5-63:19 to override.
`

I believe by simply removing the _android:allowBackup_ part at  [this](https://github.com/jhonnyx2012/HorizontalPicker/blob/2510f799d932e514d1dea71b2cfeeee05e7100bb/horizontal-picker/src/main/AndroidManifest.xml#L4) line it would fix this issue. I will see if I can create a PR for this, but thought I would create the issue in the meantime until I get around to it.

[This](https://medium.com/@elye.project/2-lines-in-manifest-to-remove-when-sharing-your-android-library-565d4c4af04a)  article gives some more background

**Comment by jhonnyx2012** [comment]
Hi, it's been a while since I release this library and I haven't been compromised with it, I understand that there are many bugs, I'd love to check them all, but I'm really busy at other projects,  so I have to apologize and recommend you to fork this project or make me a PR, I'l review it ASAP.

Cheers!

**Comment by dabarnard** [comment]
No problem @jhonnyx2012 . I have created the PR which removes those lines from the manifest. Thanks again for your library and all the best
