### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by milosmns** [jhonnyx2012/HorizontalPicker#2]
Dude this needs to be in English, it's great. Can you do it yourself? I can help with that if you need it :)

Also, 'horizontal picker' is not really a good name, it might collide with other number pickers (trust me, I know) - consider changing to horizontal 'date' picker.

Cheers

**Comment by jhonnyx2012** [comment]
Hi Milos!, thanks for your comment, i'm currently a little busy, but I really want to make the changes that you are saying. 
The name is HorizontalPicker because this project was defined as a Picker of whatever at the beginning, but by some things it finished as a DatePicker hahaha.

**Comment by milosmns** [comment]
Oh xD Well, still - I did some similar things, if you need help, do yell :)

**Comment by mrizwan2018** [comment]
visibility gone and visible is not working. when i set visibility visible of picker  it show unrecognized string instead of showing dates. can you fix it immediately??

**Comment by milosmns** [comment]
Sure, create a ticket and assign it to me?

**Comment by jhonnyx2012** [comment]
Let's use this ticket! is assigned to you

**Comment by milosmns** [comment]
Okay, I'll look into it. How urgent is it?

**Comment by jhonnyx2012** [comment]
Take your time, and thank you so much!

**Comment by milosmns** [comment]
I'm traveling this week, but I'll try to do it over the weekend :) So just the readme then?

**Comment by jhonnyx2012** [comment]
yes, just the readme please, and don't worry, have a nice trip!

**Comment by milosmns** [comment]
Added a pull request #9 - pls check it out :)

**Comment by jhonnyx2012** [comment]
It's merged now milos, thank you so much, It's amazing for me to find people like you, who cares to help others, I'm grateful, if you need something just contact me, greetings!

**Comment by milosmns** [comment]
Not a problem really :) Great library 👍
