### ISSUE TITLE
Change DEFAULT_DAYS_TO_PLUS

### ISSUE THREAD

**Issue by cremain** [jhonnyx2012/HorizontalPicker#29]
Hello

In your description we have: **Configurable number of generated days (default: 120)**.

How can chage this value?

**Comment by jhonnyx2012** [comment]
Just read the readme, is the first config after the listener `.setDays(NUMBER)`, also, just created branch `kotlin-migration-and-gradle-update` that updates gradle plugin to the latest, implement android x, and translate everything to kotlin, comming soon bug fixing and improvements, let me know if that works for you
