### ISSUE TITLE
visibility gone and hide issue.

### ISSUE THREAD

**Issue by mrizwan2018** [jhonnyx2012/HorizontalPicker#3]
visibility gone and visible is not working. when i set visibility visible of picker it show unrecognized string instead of showing dates. can you fix it immediately??

**Comment by jhonnypapinotas** [comment]
Hi, i'm going to check it, but I can't right now, my computer has issues, so, excuse me about this, by the way if you got a solution, please, let me know it

**Comment by mrizwan2018** [comment]
can't get yet

**Comment by mrizwan2018** [comment]
actually i have 2 different layout, i add one layout dynamically to my activity, when i add 2nd layout in which include HorizontalPicker then it create problem otherwise its fine.

**Comment by mrizwan2018** [comment]
and how can i change text  color of selected date?

**Comment by mrizwan2018** [comment]
even background color of view is not changing

**Comment by jhonnyx2012** [comment]
Hi!, thanks for the comments, all the customizations are available now on the 1.0.6 version, please, check de readme, Greetings.
