### ISSUE TITLE
Gradle 7 & JCenter

### ISSUE THREAD

**Issue by KennyBrunton** [jhonnyx2012/HorizontalPicker#31]
It doesn't seem to be possible to use this with Gradle 7 and Jcentre being depreciated.

**Comment by jhonnyx2012** [comment]
hey!, just created branch `kotlin-migration-and-gradle-update` that updates gradle plugin to the latest, implement android x, and translate everything to kotlin, comming soon bug fixing and improvements, let me know if that works for you
